Clean architecture
ProductDock/rbc-library-catalog pull request #65
Opened 2022-07-06 11:50 UTC by NenadBecanovicPD

2022-07-08 09:09 UTC, vukomanv-pd requested changes

2022-07-08 09:09 UTC, vukomanv-pd commented on src/main/java/com/productdock/domain/Book.java
> +        } else {
If we add a return; in the if's body, we can avoid the else block.

2022-07-08 10:59 UTC, vukomanv-pd approved these changes
LGTM 🥇

2022-07-08 11:27 UTC, dusanpetrovicpd requested changes
Exceptions are also part of domain.
We don't use Postgres database. Maybe rename packages to "sql" because we use Mysql locally and Cloud Sql on gcp

🍬

2022-07-08 11:27 UTC, dusanpetrovicpd commented on src/main/java/com/productdock/adapter/out/postgresql/BookJpaRepository.java
>              select b from BookEntity b
I think we are not using this method after introducing search-service

2022-07-08 11:27 UTC, dusanpetrovicpd commented on src/main/java/com/productdock/adapter/out/postgresql/ReviewJpaRepository.java
>      List<ReviewEntity> findByBookId(Long bookId);
Same here, check if method is needed?

2022-07-08 11:27 UTC, dusanpetrovicpd commented on src/main/java/com/productdock/application/service/PublishNewRatingService.java
> +        bookMessagingOutPort.sendMessage(kafkaTopic, new BookRatingMessage(bookId, book.getRating().getScore(), book.getRating().getCount()));
Application service should send domain object to out port. Then in out port implementation we convert it to message.

2022-07-08 11:27 UTC, dusanpetrovicpd commented on src/test/java/com/productdock/integration/BookApiTest.java
>  class BookApiTest extends KafkaTestBase {
Now we have multiple API classes, so split integration tests by them.

2022-07-12 08:23 UTC, milicazivkov85 commented on src/test/java/com/productdock/application/service/GetBookServiceShould.java
> +        assertThat(book).isInstanceOf(Book.class);
It is better to check if book is referencing the same BOOK object. Checking type is kind of obsolete in strongly typed language.

2022-07-12 08:28 UTC, milicazivkov85 commented on src/main/java/com/productdock/adapter/out/sql/BookPersistenceAdapter.java
> +        Optional<BookJpaEntity> bookEntity = bookRepository.findById(bookId);
Try this line instead of entire method body, it should map only when optional is present, and return empty optional when it's not.
`bookRepository.findById(bookId).map(bookJpaEntity -> bookMapper.toDomain(bookJpaEntity));`

(same in ReviewPersistenceAdapter)

2022-07-12 11:14 UTC, dusanpetrovicpd approved these changes
LCTM! 🇪🇸

2022-07-12 11:50 UTC, milicazivkov85 approved these changes

2022-07-12 11:56 UTC, merged