96 admin portal delete book
ProductDock/rbc-library-catalog pull request #97
Opened 2024-03-08 14:09 UTC by NenadJeckovic

Added delete book functionality with tests.

2024-03-12 09:33 UTC, djordjemijailovicpd commented on src/main/java/com/productdock/application/service/DeleteBookService.java
> +public class DeleteBookService implements DeleteBookUseCase {
Should we use package private for implementations?

2024-03-12 09:37 UTC, djordjemijailovicpd commented on src/main/java/com/productdock/application/service/DeleteBookService.java
> +        return "Book is " + status + " by " + userName + ".";
Should we use String.format()

2024-03-12 09:40 UTC, djordjemijailovicpd commented on src/main/java/com/productdock/application/service/DeleteBookService.java
> +        if (bookRepository.findById(bookId).isEmpty()) {
Extract validation into method

2024-03-13 12:34 UTC, djordjemijailovicpd commented on pom.xml
> +		<dependency>
Yes

2024-03-13 12:34 UTC, djordjemijailovicpd commented on src/main/java/com/productdock/adapter/out/kafka/DeletedBookMessagePublisher.java
> +    public void sendMessage(Long bookId) throws ExecutionException, InterruptedException, JsonProcessingException {
Decided to leave it just to have same style as old code

2024-03-13 12:35 UTC, djordjemijailovicpd commented on src/main/java/com/productdock/adapter/in/web/DeleteBookApi.java
> +        log.debug("DELETE request recieved with book id: {}", bookId);
done

2024-03-13 12:35 UTC, djordjemijailovicpd commented on src/main/java/com/productdock/application/port/out/messaging/DeleteBookMessagingOutPort.java
> +    void sendMessage(Long bookId) throws ExecutionException, InterruptedException, JsonProcessingException;
Decided to leave it just to have same style as old code

2024-03-13 12:43 UTC, djordjemijailovicpd commented on src/main/java/com/productdock/adapter/out/web/RentalsApi.java
> +public class RentalsApi implements RentalsClient {
Decision is to rename `RentalsApi` class to `RentalsApiClient`

2024-03-13 12:47 UTC, djordjemijailovicpd commented on src/main/java/com/productdock/domain/exception/DeleteBookException.java
> +@ResponseStatus(code = HttpStatus.BAD_REQUEST)
Decided to leave as is because it's done like this in all places in all services

2024-03-13 12:47 UTC, djordjemijailovicpd commented on src/main/java/com/productdock/domain/exception/BookNotFoundException.java
> +@ResponseStatus(code = HttpStatus.NOT_FOUND)
Decided to leave as is because it's done like this in all places in all services

2024-03-13 13:00 UTC, djordjemijailovicpd commented on src/test/java/com/productdock/adapter/in/web/DeleteBookApiShould.java
> +    public static final long DEFAULT_BOOK_ID = 1;
done

2024-03-13 13:25 UTC, djordjemijailovicpd approved these changes

2024-03-14 11:12 UTC, sinisatutus commented on src/main/java/com/productdock/adapter/out/web/RentalsApiClient.java
> +    @Autowired
Can this @Autowired be deleted? I guess it will still work

2024-03-14 11:20 UTC, sinisatutus commented on src/main/java/com/productdock/application/service/DeleteBookService.java
> +        deleteBookMessagingOutPort.sendMessage(bookId);
What if `sendMessage` fails for some reason? Do we want to delete a book without notifying everyone else?
Any idea how to prevent this?

2024-03-14 11:29 UTC, sinisatutus commented on src/main/java/com/productdock/application/service/DeleteBookService.java
> +        return message;
How will this message look like if the bookRentals has more than one element? Let's say we have two copies of the same book and both are rented.
My guess it would be something like:
"Book is rented by sinisa.tutus. rented by nenad.jeckovic"
I'm not saying it is bad, just is this what you wanted (assuming I recreated the message correctly 😄 )?

2024-03-14 11:31 UTC, sinisatutus commented on src/main/java/com/productdock/application/service/DeleteBookService.java
> +        return message;
Also if this happens `if (rental.status() == null || rental.user() == null)` it will return `Cannot read rental status.` regardless of what we generated in the `message` before (also the case when we have more than one element in the list)

2024-03-14 14:49 UTC, dusanpetrovicpd requested changes

2024-03-14 14:49 UTC, dusanpetrovicpd commented on src/main/java/com/productdock/application/service/DeleteBookService.java
> +        validate(bookId);
Give it a bit more context with naming of this method. Method is private so it's ok to have a longer name

2024-03-14 14:49 UTC, dusanpetrovicpd commented on src/main/java/com/productdock/adapter/in/web/dto/BookRentalStateDto.java
> +
And does it need to be part of `adapter` layer or part of `domain`?

2024-03-14 14:49 UTC, dusanpetrovicpd commented on src/test/java/com/productdock/integration/DeleteBookApiTest.java
> +    void deleteBook_whenIdDoesntExist() throws Exception {
You can use `@SneakyThrows`, because it's not important on this level to say that method throws Exception

2024-03-14 14:49 UTC, dusanpetrovicpd commented on src/test/java/com/productdock/application/service/DeleteBookServiceShould.java
> +    void ThrowExceptionWhenBookDoesntExist(){
`T` ->`t`

2024-03-14 14:49 UTC, dusanpetrovicpd commented on src/test/java/com/productdock/application/service/DeleteBookServiceShould.java
> +    void ThrowExceptionWhenBookIsTaken() throws IOException, InterruptedException {
`T` ->`t`

2024-03-14 14:49 UTC, dusanpetrovicpd commented on src/test/java/com/productdock/application/service/DeleteBookServiceShould.java
> +                .isInstanceOf(DeleteBookException.class);
Also here, for this type of exception you want to check the exception message also
You will have more test cases for that

2024-03-25 09:31 UTC, dusanpetrovicpd approved these changes

2024-03-25 09:40 UTC, merged